using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RDM : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public byte RdmStartCode = 0xCC; //SC_RDM
    public byte RdmSubStartCode = 0x01; //SC_Sub_Message

    public enum RDMCommandClasses
    {
        DISCOVERY_COMMAND = 0x10,
        DISCOVERY_COMMAND_RESPONSE = 0x11,
        GET_COMMAND = 0x20,
        GET_COMMAND_RESPONSE = 0x21,
        SET_COMMAND = 0x30,
        SET_COMMAND_RESPONSE = 0x31,
    }

    public enum RDMResponseType
    {
        RESPONSE_TYPE_ACK = 0x00,
        RESPONSE_TYPE_ACK_TIMER = 0x01,
        RESPONSE_TYPE_NACK_REASON = 0x02,
        RESPONSE_TYPE_ACK_OVERFLOW = 0x03,
    }

    public enum RDMParameterIDs
    {
        NetworkManagement_DISC_UNIQUE_BRANCH = 0x0001,
        NetworkManagement_DISC_MUTE = 0x0002,
        NetworkManagement_DISC_UN_MUTE = 0x0003,
        NetworkManagement_PROXIED_DEVICES = 0x0010,
        NetworkManagement_PROXIED_DEVICE_COUNT = 0x0011,
        NetworkManagement_COMMS_STATUS = 0x0015,
        StatusCollection_QUEUED_MESSAGE = 0x0020,
        StatusCollection_STATUS_MESSAGES = 0x0030,
        StatusCollection_STATUS_ID_DESCRIPTION = 0x0031,
        StatusCollection_CLEAR_STATUS_ID = 0x0032,
        StatusCollection_SUB_DEVICE_STATUS_REPORT_THRESHOLD = 0x0033,
        RdmInfomation_SUPPORTED_PARAMETERS = 0X0050,
        RdmInfomation_PARAMETER_DESCRIPTION = 0X0051,
        ProductInfomation_DEVICE_INFO = 0x0060,
        ProductInfomation_PRODUCT_DETAIL_ID_LIST = 0x0070,
        ProductInfomation_DEVICE_MODEL_DESCRIPTION = 0x0080,
        ProductInfomation_MANUFACTURER_LABEL = 0x0081,
        ProductInfomation_DEVICE_LABEL = 0x0082,
        ProductInfomation_FACTORY_DEFAULTS = 0x0090,
        ProductInfomation_LANGUAGE_CAPABILITIES = 0x00A0,
        ProductInfomation_LANGUAGE = 0x00B0,
        ProductInfomation_SOFTWARE_VERSION_LABEL = 0x00C0,
        ProductInfomation_BOOT_SOFTWARE_VERSION_ID = 0x00C1,
        ProductInfomation_BOOT_SOFTWARE_VERSION_LABEL = 0x00C2,
        Dmx512Setup_DMX_PERSONALITY = 0x00E0,
        Dmx512Setup_DMX_PERSONALITY_DESCRIPTION = 0x00E1,
        Dmx512Setup_DMX_START_ADDRESS = 0x00F0,
        Dmx512Setup_SLOT_INFO = 0x0120,
        Dmx512Setup_SLOT_DESCRIPTION = 0x0121,
        Dmx512Setup_DEFAULT_SLOT_VALUE = 0x0122,
        Sensors_SENSOR_DEFINITION = 0x0200,
        Sensors_VALUE = 0x0201,
        Sensors_RECORD_SENSORS = 0x0202,
        PowerLampSettings_DEVICE_HOURS = 0x0400,
        PowerLampSettings_LAMP_HOURS = 0x0401,
        PowerLampSettings_LAMP_STRIKES = 0x0402,
        PowerLampSettings_LAMP_STATE = 0x0403,
        PowerLampSettings_LAMP_ON_MODE = 0x0404,
        PowerLampSettings_DEVICE_POWER_CYCLES = 0x0405,
        DisplaySettings_DISPLAY_INVERT = 0x0500,
        DisplaySettings_DISPLAY_LEVEL = 0x0501,
        Configuration_PAN_INVERT = 0x0600,
        Configuration_TILT_INVERT = 0x0601,
        Configuration_PAN_TILT_SWAP = 0x0602,
        Configuration_REAL_TIME_CLOCK = 0x0603,
        Control_IDENTIFY_DEVICE = 0x1000,
        Control_RESET_DEVICE = 0x1001,
        Control_POWER_STATE = 0x1010,
        Control_PERFORM_SELFTEST = 0x1020,
        Control_SELF_TEST_DESCRIPTION = 0x1021,
        Control_CAPTURE_PRESET = 0x1030,
        Control_PRESET_PLAYBACK = 0x1031,

    }

    /// <summary>
    /// Used for RDM Commands (RDMParameterIDs): StatusCollection_QUEUED_MESSAGE and StatusCollection_STATUS_MESSAGES and StatusCollection_SUB_DEVICE_STATUS_REPORT_THRESHOLD
    /// </summary>
    public enum StatusMessageTypes
    {
        STATUS_NONE = 0x00,
        STATUS_GET_LAST_MESSAGE = 0x01,
        STATUS_ADVISORY = 0x02,
        STATUS_WARNING = 0x03,
        STATUS_ERROR = 0x04,
        STATUS_ADVISORY_CLEARED = 0x12,
        STATUS_WARNING_CLEARED = 0x13,
        STATUS_ERROR_CLEARED = 0x14
    }

    /// <summary>
    /// Categories for device.
    /// 0x[MSB][LSB]
    /// </summary>
    public enum ProductCategories
    {
        PRODUCT_CATEGORY_NOT_DECLARED = 0x0000,
        PRODUCT_CATEGORY_FIXTURE = 0x0100,
        PRODUCT_CATEGORY_FIXTURE_FIXED = 0x0101,
        PRODUCT_CATEGORY_FIXTURE_MOVING_YOKE = 0x0102,
        PRODUCT_CATEGORY_FIXTURE_MOVING_MIRROR = 0x0103,
        PRODUCT_CATEGORY_FIXTURE_OTHER = 0x01FF,
        PRODUCT_CATEGORY_FIXTURE_ACCESSORY = 0x0200,
        PRODUCT_CATEGORY_FIXTURE_ACCESSORY_COLOR = 0x0201,
        PRODUCT_CATEGORY_FIXTURE_ACCESSORY_YOKE = 0x0202,
        PRODUCT_CATEGORY_FIXTURE_ACCESSORY_MIRROR = 0x0203,
        PRODUCT_CATEGORY_FIXTURE_ACCESSORY_EFFECT = 0x0204,
        PRODUCT_CATEGORY_FIXTURE_ACCESSORY_BEAM = 0x0205,
        PRODUCT_CATEGORY_FIXTURE_ACCESSORY_OTHER = 0x02FF,
        PRODUCT_CATEGORY_PROJECTOR = 0x0300,
        PRODUCT_CATEGORY_PROJECTOR_FIXED = 0x0301,
        PRODUCT_CATEGORY_PROJECTOR_MOVING_YOKE = 0x0302,
        PRODUCT_CATEGORY_PROJECTOR_MOVING_MIRROR = 0x0303,
        PRODUCT_CATEGORY_PROJECTOR_OTHER = 0x03FF,
        PRODUCT_CATEGORY_ATMOSPHERIC = 0x0400,
        PRODUCT_CATEGORY_ATMOSPHERIC_EFFECT = 0x0401,
        PRODUCT_CATEGORY_ATMOSPHERIC_PYRO = 0x0402,
        PRODUCT_CATEGORY_ATMOSPHERIC_OTHER = 0x04FF,
        PRODUCT_CATEGORY_DIMMER = 0x0500,
        PRODUCT_CATEGORY_DIMMER_AC_INCANDESCENT = 0x0501,
        PRODUCT_CATEGORY_DIMMER_AC_FLUORESCENT = 0x0502,
        PRODUCT_CATEGORY_DIMMER_AC_COLDCATHODE = 0x0503,
        PRODUCT_CATEGORY_DIMMER_AC_NONDIM = 0x0504,
        PRODUCT_CATEGORY_DIMMER_AC_ELV = 0x0505,
        PRODUCT_CATEGORY_DIMMER_AC_OTHER = 0x0506,
        PRODUCT_CATEGORY_DIMMER_DC_LEVEL = 0x0507,
        PRODUCT_CATEGORY_DIMMER_DC_PWM = 0x0508,
        PRODUCT_CATEGORY_DIMMER_CS_LED = 0x0509,
        PRODUCT_CATEGORY_DIMMER_OTHER = 0x05FF,
        PRODUCT_CATEGORY_POWER = 0x0600,
        PRODUCT_CATEGORY_POWER_CONTROL = 0x0601,
        PRODUCT_CATEGORY_POWER_SOURCE = 0x0602,
        PRODUCT_CATEGORY_POWER_OTHER = 0x06FF,
        PRODUCT_CATEGORY_SCENIC = 0x0700,
        PRODUCT_CATEGORY_SCENIC_DRIVE = 0x0701,
        PRODUCT_CATEGORY_SCENIC_OTHER = 0x07FF,
        PRODUCT_CATEGORY_DATA = 0x0800,
        PRODUCT_CATEGORY_DATA_DISTRIBUTION = 0x0801,
        PRODUCT_CATEGORY_DATA_CONVERSION = 0x0802,
        PRODUCT_CATEGORY_DATA_OTHER = 0x08FF,
        PRODUCT_CATEGORY_AV = 0x0900,
        PRODUCT_CATEGORY_AV_AUDIO = 0x0901,
        PRODUCT_CATEGORY_AV_VIDEO = 0x0902,
        PRODUCT_CATEGORY_AV_OTHER = 0x09FF,
        PRODUCT_CATEGORY_MONITOR = 0x0A00,
        PRODUCT_CATEGORY_MONITOR_ACLINEPOWER = 0x0A01,
        PRODUCT_CATEGORY_MONITOR_DCPOWER = 0x0A02,
        PRODUCT_CATEGORY_MONITOR_ENVIRONMENTAL = 0x0A03,
        PRODUCT_CATEGORY_MONITOR_OTHER = 0x0AFF,
        PRODUCT_CATEGORY_CONTROL = 0x7000,
        PRODUCT_CATEGORY_CONTROL_CONTROLLER = 0x7001,
        PRODUCT_CATEGORY_CONTROL_BACKUPDEVICE = 0x7002,
        PRODUCT_CATEGORY_CONTROL_OTHER = 0x70FF,
        PRODUCT_CATEGORY_TEST = 0x7100,
        PRODUCT_CATEGORY_TEST_EQUIPMENT = 0x7101,
        PRODUCT_CATEGORY_TEST_EQUIPMENT_OTHER = 0x71FF,
        PRODUCT_CATEGORY_OTHER = 0x7FFF
    }


    public enum ProductDetail
    {
        PRODUCT_DETAIL_NOT_DECLARED = 0x0000,
        PRODUCT_DETAIL_ARC = 0x0001,
        PRODUCT_DETAIL_METAL_HALIDE = 0x0002,
        PRODUCT_DETAIL_INCANDESCENT = 0x0003,
        PRODUCT_DETAIL_LED = 0x0004,
        PRODUCT_DETAIL_FLUROESCENT = 0x0005,
        PRODUCT_DETAIL_COLDCATHODE = 0x0006,
        PRODUCT_DETAIL_ELECTROLUMINESCENT = 0x0007,
        PRODUCT_DETAIL_LASER = 0x0008,
        PRODUCT_DETAIL_FLASHTUBE = 0x0009,
        PRODUCT_DETAIL_COLORSCROLLER = 0x0100,
        PRODUCT_DETAIL_COLORWHEEL = 0x0101,
        PRODUCT_DETAIL_COLORCHANGE = 0x0102,
        PRODUCT_DETAIL_IRIS_DOUSER = 0x0103,
        PRODUCT_DETAIL_DIMMING_SHUTTER = 0x0104,
        PRODUCT_DETAIL_PROFILE_SHUTTER = 0x0105,
        PRODUCT_DETAIL_BARNDOOR_SHUTTER = 0x0106,
        PRODUCT_DETAIL_EFFECTS_DISC = 0x0107,
        PRODUCT_DETAIL_GOBO_ROTATOR = 0x0108,
        PRODUCT_DETAIL_VIDEO = 0x0200,
        PRODUCT_DETAIL_SLIDE = 0x0201,
        PRODUCT_DETAIL_FILM = 0x0202,
        PRODUCT_DETAIL_OILWHEEL = 0x0203,
        PRODUCT_DETAIL_LCDGATE = 0x0204,
        PRODUCT_DETAIL_FOGGER_GLYCOL = 0x0300,
        PRODUCT_DETAIL_FOGGER_MINERALOIL = 0x0301,
        PRODUCT_DETAIL_FOGGER_WATER = 0x0302,
        PRODUCT_DETAIL_C02 = 0x0303,
        PRODUCT_DETAIL_LN2 = 0x0304,
        PRODUCT_DETAIL_BUBBLE = 0x0305,
        PRODUCT_DETAIL_FLAME_PROPANE = 0x0306,
        PRODUCT_DETAIL_FLAME_OTHER = 0x0307,
        PRODUCT_DETAIL_OLEFACTORY_STIMULATOR = 0x0308,
        PRODUCT_DETAIL_SNOW = 0x0309,
        PRODUCT_DETAIL_WATER_JET = 0x030A,
        PRODUCT_DETAIL_WIND = 0x030B,
        PRODUCT_DETAIL_CONFETTI = 0x030C,
        PRODUCT_DETAIL_HAZARD = 0x030D,
        PRODUCT_DETAIL_PHASE_CONTROL = 0x0400,
        PRODUCT_DETAIL_REVERSE_PHASE_CONTROL = 0x0401,
        PRODUCT_DETAIL_SINE = 0x0402,
        PRODUCT_DETAIL_PWM = 0x0403,
        PRODUCT_DETAIL_DC = 0x0404,
        PRODUCT_DETAIL_HFBALLAST = 0x0405,
        PRODUCT_DETAIL_HFHV_NEONBALLAST = 0x0406,
        PRODUCT_DETAIL_HFHV_EL = 0x0407,
        PRODUCT_DETAIL_MHR_BALLAST = 0x0408,
        PRODUCT_DETAIL_BITANGLE_MODULATION = 0x0409,
        PRODUCT_DETAIL_FREQUENCY_MODULATION = 0x040A,
        PRODUCT_DETAIL_HIGHFREQUENCY_12V = 0x040B,
        PRODUCT_DETAIL_RELAY_MECHANICAL = 0x040C,
        PRODUCT_DETAIL_RELAY_ELECTRONIC = 0x040D,
        PRODUCT_DETAIL_SWITCH_ELECTRONIC = 0x040E,
        PRODUCT_DETAIL_CONTACTOR = 0x040F,
        PRODUCT_DETAIL_MIRRORBALL_ROTATOR = 0x0500,
        PRODUCT_DETAIL_OTHER_ROTATOR = 0x0501,
        PRODUCT_DETAIL_KABUKI_DROP = 0x0502,
        PRODUCT_DETAIL_CURTAIN = 0x0503,
        PRODUCT_DETAIL_LINESET = 0x0504,
        PRODUCT_DETAIL_MOTOR_CONTROL = 0x0505,
        PRODUCT_DETAIL_DAMPER_CONTROL = 0x0506,
        PRODUCT_DETAIL_SPLITTER = 0x0600,
        PRODUCT_DETAIL_ETHERNET_NODE = 0x0601,
        PRODUCT_DETAIL_MERGE = 0x0602,
        PRODUCT_DETAIL_DATAPATCH = 0x0603,
        PRODUCT_DETAIL_WIRELESS_LINK = 0x0604,
        PRODUCT_DETAIL_PROTOCOL_CONVERTOR = 0x0701,
        PRODUCT_DETAIL_ANALOG_DEMULTIPLEX = 0x0702,
        PRODUCT_DETAIL_ANALOG_MULTIPLEX = 0x0703,
        PRODUCT_DETAIL_SWITCH_PANEL = 0x0704,
        PRODUCT_DETAIL_ROUTER = 0x0800,
        PRODUCT_DETAIL_FADER = 0x0801,
        PRODUCT_DETAIL_MIXER = 0x0802,
        PRODUCT_DETAIL_CHANGEOVER_MANUAL = 0x0900,
        PRODUCT_DETAIL_CHANGEOVER_AUTO = 0x0901,
        PRODUCT_DETAIL_TEST = 0x0902,
        PRODUCT_DETAIL_GFI_RCD = 0x0A00,
        PRODUCT_DETAIL_BATTERY = 0x0A01,
        PRODUCT_DETAIL_CONTROLLABLE_BREAKER = 0x0A02,
        PRODUCT_DETAIL_OTHER = 0x7FFF,
  
    }

}
