using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RDM { 
 

    public byte RdmStartCode = 0xCC; //SC_RDM
    public byte RdmSubStartCode = 0x01; //SC_Sub_Message

    public enum RDMCommandClasses
    {
        DISCOVERY_COMMAND = 0x10,
        DISCOVERY_COMMAND_RESPONSE = 0x11,
        GET_COMMAND = 0x20,
        GET_COMMAND_RESPONSE = 0x21,
        SET_COMMAND = 0x30,
        SET_COMMAND_RESPONSE = 0x31,
    }

    public enum RDMResponseType
    {
        RESPONSE_TYPE_ACK = 0x00,
        RESPONSE_TYPE_ACK_TIMER = 0x01,
        RESPONSE_TYPE_NACK_REASON = 0x02,
        RESPONSE_TYPE_ACK_OVERFLOW = 0x03,
    }

    public enum RDMParameterIDs
    {
        NetworkManagement_DISC_UNIQUE_BRANCH = 0x0001,
        NetworkManagement_DISC_MUTE = 0x0002,
        NetworkManagement_DISC_UN_MUTE = 0x0003,
        NetworkManagement_PROXIED_DEVICES = 0x0010,
        NetworkManagement_PROXIED_DEVICE_COUNT = 0x0011,
        NetworkManagement_COMMS_STATUS = 0x0015,
        StatusCollection_QUEUED_MESSAGE = 0x0020,
        StatusCollection_STATUS_MESSAGES = 0x0030,
        StatusCollection_STATUS_ID_DESCRIPTION = 0x0031,
        StatusCollection_CLEAR_STATUS_ID = 0x0032,
        StatusCollection_SUB_DEVICE_STATUS_REPORT_THRESHOLD = 0x0033,
        RdmInfomation_SUPPORTED_PARAMETERS = 0X0050,
        RdmInfomation_PARAMETER_DESCRIPTION = 0X0051,
        ProductInfomation_DEVICE_INFO = 0x0060,
        ProductInfomation_PRODUCT_DETAIL_ID_LIST = 0x0070,
        ProductInfomation_DEVICE_MODEL_DESCRIPTION = 0x0080,
        ProductInfomation_MANUFACTURER_LABEL = 0x0081,
        ProductInfomation_DEVICE_LABEL = 0x0082,
        ProductInfomation_FACTORY_DEFAULTS = 0x0090,
        ProductInfomation_LANGUAGE_CAPABILITIES = 0x00A0,
        ProductInfomation_LANGUAGE = 0x00B0,
        ProductInfomation_SOFTWARE_VERSION_LABEL = 0x00C0,
        ProductInfomation_BOOT_SOFTWARE_VERSION_ID = 0x00C1,
        ProductInfomation_BOOT_SOFTWARE_VERSION_LABEL = 0x00C2,
        Dmx512Setup_DMX_PERSONALITY = 0x00E0,
        Dmx512Setup_DMX_PERSONALITY_DESCRIPTION = 0x00E1,
        Dmx512Setup_DMX_START_ADDRESS = 0x00F0,
        Dmx512Setup_SLOT_INFO = 0x0120,
        Dmx512Setup_SLOT_DESCRIPTION = 0x0121,
        Dmx512Setup_DEFAULT_SLOT_VALUE = 0x0122,
        Sensors_SENSOR_DEFINITION = 0x0200,
        Sensors_VALUE = 0x0201,
        Sensors_RECORD_SENSORS = 0x0202,
        PowerLampSettings_DEVICE_HOURS = 0x0400,
        PowerLampSettings_LAMP_HOURS = 0x0401,
        PowerLampSettings_LAMP_STRIKES = 0x0402,
        PowerLampSettings_LAMP_STATE = 0x0403,
        PowerLampSettings_LAMP_ON_MODE = 0x0404,
        PowerLampSettings_DEVICE_POWER_CYCLES = 0x0405,
        DisplaySettings_DISPLAY_INVERT = 0x0500,
        DisplaySettings_DISPLAY_LEVEL = 0x0501,
        Configuration_PAN_INVERT = 0x0600,
        Configuration_TILT_INVERT = 0x0601,
        Configuration_PAN_TILT_SWAP = 0x0602,
        Configuration_REAL_TIME_CLOCK = 0x0603,
        Control_IDENTIFY_DEVICE = 0x1000,
        Control_RESET_DEVICE = 0x1001,
        Control_POWER_STATE = 0x1010,
        Control_PERFORM_SELFTEST = 0x1020,
        Control_SELF_TEST_DESCRIPTION = 0x1021,
        Control_CAPTURE_PRESET = 0x1030,
        Control_PRESET_PLAYBACK = 0x1031,

    }

    /// <summary>
    /// Used for RDM Commands (RDMParameterIDs): StatusCollection_QUEUED_MESSAGE and StatusCollection_STATUS_MESSAGES and StatusCollection_SUB_DEVICE_STATUS_REPORT_THRESHOLD
    /// </summary>
    public enum StatusMessageTypes
    {
        STATUS_NONE = 0x00,
        STATUS_GET_LAST_MESSAGE = 0x01,
        STATUS_ADVISORY = 0x02,
        STATUS_WARNING = 0x03,
        STATUS_ERROR = 0x04,
        STATUS_ADVISORY_CLEARED = 0x12,
        STATUS_WARNING_CLEARED = 0x13,
        STATUS_ERROR_CLEARED = 0x14
    }

    /// <summary>
    /// Categories for device.
    /// 0x[MSB][LSB]
    /// </summary>
    public enum ProductCategories
    {
        PRODUCT_CATEGORY_NOT_DECLARED = 0x0000,
        PRODUCT_CATEGORY_FIXTURE = 0x0100,
        PRODUCT_CATEGORY_FIXTURE_FIXED = 0x0101,
        PRODUCT_CATEGORY_FIXTURE_MOVING_YOKE = 0x0102,
        PRODUCT_CATEGORY_FIXTURE_MOVING_MIRROR = 0x0103,
        PRODUCT_CATEGORY_FIXTURE_OTHER = 0x01FF,
        PRODUCT_CATEGORY_FIXTURE_ACCESSORY = 0x0200,
        PRODUCT_CATEGORY_FIXTURE_ACCESSORY_COLOR = 0x0201,
        PRODUCT_CATEGORY_FIXTURE_ACCESSORY_YOKE = 0x0202,
        PRODUCT_CATEGORY_FIXTURE_ACCESSORY_MIRROR = 0x0203,
        PRODUCT_CATEGORY_FIXTURE_ACCESSORY_EFFECT = 0x0204,
        PRODUCT_CATEGORY_FIXTURE_ACCESSORY_BEAM = 0x0205,
        PRODUCT_CATEGORY_FIXTURE_ACCESSORY_OTHER = 0x02FF,
        PRODUCT_CATEGORY_PROJECTOR = 0x0300,
        PRODUCT_CATEGORY_PROJECTOR_FIXED = 0x0301,
        PRODUCT_CATEGORY_PROJECTOR_MOVING_YOKE = 0x0302,
        PRODUCT_CATEGORY_PROJECTOR_MOVING_MIRROR = 0x0303,
        PRODUCT_CATEGORY_PROJECTOR_OTHER = 0x03FF,
        PRODUCT_CATEGORY_ATMOSPHERIC = 0x0400,
        PRODUCT_CATEGORY_ATMOSPHERIC_EFFECT = 0x0401,
        PRODUCT_CATEGORY_ATMOSPHERIC_PYRO = 0x0402,
        PRODUCT_CATEGORY_ATMOSPHERIC_OTHER = 0x04FF,
        PRODUCT_CATEGORY_DIMMER = 0x0500,
        PRODUCT_CATEGORY_DIMMER_AC_INCANDESCENT = 0x0501,
        PRODUCT_CATEGORY_DIMMER_AC_FLUORESCENT = 0x0502,
        PRODUCT_CATEGORY_DIMMER_AC_COLDCATHODE = 0x0503,
        PRODUCT_CATEGORY_DIMMER_AC_NONDIM = 0x0504,
        PRODUCT_CATEGORY_DIMMER_AC_ELV = 0x0505,
        PRODUCT_CATEGORY_DIMMER_AC_OTHER = 0x0506,
        PRODUCT_CATEGORY_DIMMER_DC_LEVEL = 0x0507,
        PRODUCT_CATEGORY_DIMMER_DC_PWM = 0x0508,
        PRODUCT_CATEGORY_DIMMER_CS_LED = 0x0509,
        PRODUCT_CATEGORY_DIMMER_OTHER = 0x05FF,
        PRODUCT_CATEGORY_POWER = 0x0600,
        PRODUCT_CATEGORY_POWER_CONTROL = 0x0601,
        PRODUCT_CATEGORY_POWER_SOURCE = 0x0602,
        PRODUCT_CATEGORY_POWER_OTHER = 0x06FF,
        PRODUCT_CATEGORY_SCENIC = 0x0700,
        PRODUCT_CATEGORY_SCENIC_DRIVE = 0x0701,
        PRODUCT_CATEGORY_SCENIC_OTHER = 0x07FF,
        PRODUCT_CATEGORY_DATA = 0x0800,
        PRODUCT_CATEGORY_DATA_DISTRIBUTION = 0x0801,
        PRODUCT_CATEGORY_DATA_CONVERSION = 0x0802,
        PRODUCT_CATEGORY_DATA_OTHER = 0x08FF,
        PRODUCT_CATEGORY_AV = 0x0900,
        PRODUCT_CATEGORY_AV_AUDIO = 0x0901,
        PRODUCT_CATEGORY_AV_VIDEO = 0x0902,
        PRODUCT_CATEGORY_AV_OTHER = 0x09FF,
        PRODUCT_CATEGORY_MONITOR = 0x0A00,
        PRODUCT_CATEGORY_MONITOR_ACLINEPOWER = 0x0A01,
        PRODUCT_CATEGORY_MONITOR_DCPOWER = 0x0A02,
        PRODUCT_CATEGORY_MONITOR_ENVIRONMENTAL = 0x0A03,
        PRODUCT_CATEGORY_MONITOR_OTHER = 0x0AFF,
        PRODUCT_CATEGORY_CONTROL = 0x7000,
        PRODUCT_CATEGORY_CONTROL_CONTROLLER = 0x7001,
        PRODUCT_CATEGORY_CONTROL_BACKUPDEVICE = 0x7002,
        PRODUCT_CATEGORY_CONTROL_OTHER = 0x70FF,
        PRODUCT_CATEGORY_TEST = 0x7100,
        PRODUCT_CATEGORY_TEST_EQUIPMENT = 0x7101,
        PRODUCT_CATEGORY_TEST_EQUIPMENT_OTHER = 0x71FF,
        PRODUCT_CATEGORY_OTHER = 0x7FFF
    }


    public enum ProductDetail
    {
        PRODUCT_DETAIL_NOT_DECLARED = 0x0000,
        PRODUCT_DETAIL_ARC = 0x0001,
        PRODUCT_DETAIL_METAL_HALIDE = 0x0002,
        PRODUCT_DETAIL_INCANDESCENT = 0x0003,
        PRODUCT_DETAIL_LED = 0x0004,
        PRODUCT_DETAIL_FLUROESCENT = 0x0005,
        PRODUCT_DETAIL_COLDCATHODE = 0x0006,
        PRODUCT_DETAIL_ELECTROLUMINESCENT = 0x0007,
        PRODUCT_DETAIL_LASER = 0x0008,
        PRODUCT_DETAIL_FLASHTUBE = 0x0009,
        PRODUCT_DETAIL_COLORSCROLLER = 0x0100,
        PRODUCT_DETAIL_COLORWHEEL = 0x0101,
        PRODUCT_DETAIL_COLORCHANGE = 0x0102,
        PRODUCT_DETAIL_IRIS_DOUSER = 0x0103,
        PRODUCT_DETAIL_DIMMING_SHUTTER = 0x0104,
        PRODUCT_DETAIL_PROFILE_SHUTTER = 0x0105,
        PRODUCT_DETAIL_BARNDOOR_SHUTTER = 0x0106,
        PRODUCT_DETAIL_EFFECTS_DISC = 0x0107,
        PRODUCT_DETAIL_GOBO_ROTATOR = 0x0108,
        PRODUCT_DETAIL_VIDEO = 0x0200,
        PRODUCT_DETAIL_SLIDE = 0x0201,
        PRODUCT_DETAIL_FILM = 0x0202,
        PRODUCT_DETAIL_OILWHEEL = 0x0203,
        PRODUCT_DETAIL_LCDGATE = 0x0204,
        PRODUCT_DETAIL_FOGGER_GLYCOL = 0x0300,
        PRODUCT_DETAIL_FOGGER_MINERALOIL = 0x0301,
        PRODUCT_DETAIL_FOGGER_WATER = 0x0302,
        PRODUCT_DETAIL_C02 = 0x0303,
        PRODUCT_DETAIL_LN2 = 0x0304,
        PRODUCT_DETAIL_BUBBLE = 0x0305,
        PRODUCT_DETAIL_FLAME_PROPANE = 0x0306,
        PRODUCT_DETAIL_FLAME_OTHER = 0x0307,
        PRODUCT_DETAIL_OLEFACTORY_STIMULATOR = 0x0308,
        PRODUCT_DETAIL_SNOW = 0x0309,
        PRODUCT_DETAIL_WATER_JET = 0x030A,
        PRODUCT_DETAIL_WIND = 0x030B,
        PRODUCT_DETAIL_CONFETTI = 0x030C,
        PRODUCT_DETAIL_HAZARD = 0x030D,
        PRODUCT_DETAIL_PHASE_CONTROL = 0x0400,
        PRODUCT_DETAIL_REVERSE_PHASE_CONTROL = 0x0401,
        PRODUCT_DETAIL_SINE = 0x0402,
        PRODUCT_DETAIL_PWM = 0x0403,
        PRODUCT_DETAIL_DC = 0x0404,
        PRODUCT_DETAIL_HFBALLAST = 0x0405,
        PRODUCT_DETAIL_HFHV_NEONBALLAST = 0x0406,
        PRODUCT_DETAIL_HFHV_EL = 0x0407,
        PRODUCT_DETAIL_MHR_BALLAST = 0x0408,
        PRODUCT_DETAIL_BITANGLE_MODULATION = 0x0409,
        PRODUCT_DETAIL_FREQUENCY_MODULATION = 0x040A,
        PRODUCT_DETAIL_HIGHFREQUENCY_12V = 0x040B,
        PRODUCT_DETAIL_RELAY_MECHANICAL = 0x040C,
        PRODUCT_DETAIL_RELAY_ELECTRONIC = 0x040D,
        PRODUCT_DETAIL_SWITCH_ELECTRONIC = 0x040E,
        PRODUCT_DETAIL_CONTACTOR = 0x040F,
        PRODUCT_DETAIL_MIRRORBALL_ROTATOR = 0x0500,
        PRODUCT_DETAIL_OTHER_ROTATOR = 0x0501,
        PRODUCT_DETAIL_KABUKI_DROP = 0x0502,
        PRODUCT_DETAIL_CURTAIN = 0x0503,
        PRODUCT_DETAIL_LINESET = 0x0504,
        PRODUCT_DETAIL_MOTOR_CONTROL = 0x0505,
        PRODUCT_DETAIL_DAMPER_CONTROL = 0x0506,
        PRODUCT_DETAIL_SPLITTER = 0x0600,
        PRODUCT_DETAIL_ETHERNET_NODE = 0x0601,
        PRODUCT_DETAIL_MERGE = 0x0602,
        PRODUCT_DETAIL_DATAPATCH = 0x0603,
        PRODUCT_DETAIL_WIRELESS_LINK = 0x0604,
        PRODUCT_DETAIL_PROTOCOL_CONVERTOR = 0x0701,
        PRODUCT_DETAIL_ANALOG_DEMULTIPLEX = 0x0702,
        PRODUCT_DETAIL_ANALOG_MULTIPLEX = 0x0703,
        PRODUCT_DETAIL_SWITCH_PANEL = 0x0704,
        PRODUCT_DETAIL_ROUTER = 0x0800,
        PRODUCT_DETAIL_FADER = 0x0801,
        PRODUCT_DETAIL_MIXER = 0x0802,
        PRODUCT_DETAIL_CHANGEOVER_MANUAL = 0x0900,
        PRODUCT_DETAIL_CHANGEOVER_AUTO = 0x0901,
        PRODUCT_DETAIL_TEST = 0x0902,
        PRODUCT_DETAIL_GFI_RCD = 0x0A00,
        PRODUCT_DETAIL_BATTERY = 0x0A01,
        PRODUCT_DETAIL_CONTROLLABLE_BREAKER = 0x0A02,
        PRODUCT_DETAIL_OTHER = 0x7FFF,
  
    }

    public enum PresetPlayback
    {
        PRESET_PLAYBACK_OFF = 0X0000,
        PRESET_PLAYBACK_ALL = 0XFFFF,
        PRESET_PLAYBACK_SCENE_01 = 0X0001, //0X0001 - 0XFFFE
        PRESET_PLAYBACK_SCENE_02 = 0X0002,
        PRESET_PLAYBACK_SCENE_03 = 0X0003,
        PRESET_PLAYBACK_SCENE_04 = 0X0004,
        PRESET_PLAYBACK_SCENE_05 = 0X0005,
        PRESET_PLAYBACK_SCENE_06 = 0X0006,
        PRESET_PLAYBACK_SCENE_07 = 0X0007,
        PRESET_PLAYBACK_SCENE_08 = 0X0008,
        PRESET_PLAYBACK_SCENE_09 = 0X0009,
        PRESET_PLAYBACK_SCENE_10 = 0X000A,
        PRESET_PLAYBACK_SCENE_11 = 0X000B,
        PRESET_PLAYBACK_SCENE_12 = 0X000C,
        PRESET_PLAYBACK_SCENE_13 = 0X000D,
        PRESET_PLAYBACK_SCENE_14 = 0X000E,
        PRESET_PLAYBACK_SCENE_15 = 0X000F,
    }

    public enum LampState
    {
        LAMP_OFF = 0x00,
        LAMP_ON = 0x01,
        LAMP_STRIKE = 0x02,
        LAMP_STANDBY = 0x03,
        LAMP_NOT_PRESENT = 0x04,
        LAMP_ERROR = 0x7F,
    }

    public enum LampMode
    {
        LAMP_ON_MODE_OFF = 0x00,
        LAMP_ON_MODE_DMX = 0x01,
        LAMP_ON_MODE_ON = 0x02,
        LAMP_ON_MODE_AFTER_CAL = 0x03,
    }

    public enum SelfTest
    {
        SELF_TEST_OFF = 0x00,
        SELF_TEST_ALL = 0xFF,
    }

    public enum PowerState
    {
        POWER_STATE_FULL_OFF = 0x00,
        POWER_STATE_SHUTDOWN = 0x01,
        POWER_STATE_STANDBY = 0x02,
        POWER_STATE_NORMAL = 0xFF,
    }

    public enum SensorType
    {
        SENS_TEMPERATURE = 0x00,
        SENS_VOLTAGE = 0x01,
        SENS_CURRENT = 0x02,
        SENS_FREQUENCY = 0x03,
        SENS_RESISTANCE = 0X04,
        SENS_POWER = 0x05,
        SENS_MASS = 0x06,
        SENS_LENGTH = 0x07,
        SENS_AERA = 0x08,
        SENS_VOLUME = 0x09,
        SENS_DENSITY = 0x0A,
        SENS_VELOCITY = 0x0B,
        SENS_ACCELERATION = 0x0C,
        SENS_FORCE = 0x0D,
        SENS_ENERGY = 0x0E,
        SENS_PRESSURE = 0x0F,
        SENS_TIME = 0x10,
        SENS_ANGLE = 0x11,
        SENS_POSITIONX = 0x12, //E.G. POSITION OF LAMP ON TRUSS
        SENS_POSITIONY = 0x13,
        SENS_POSITIONZ = 0x14,
        SENS_ANGULAR_VELOCITY = 0x15, //E.G. WIND SPEED
        SENS_LUMINOUS_INTENSITY = 0x16,
        SENS_LUMINOUS_FLUX = 0x17,
        SENS_ILLUMINANCE = 0x18,
        SENS_CHROMINANCE_RED = 0x19,
        SENS_CHROMINANCE_GREEN = 0x1A,
        SENS_CHROMINANCE_BLUE = 0x1B,
        SENS_CONTACTS = 0x1C, // SWITCH INPUTS
        SENS_MEMORY = 0x1D, //ROM SIZE
        SENS_ITEMS = 0x1E, // SCROLLER GEL FRAMES
        SENS_HUMIDITY = 0x1F,
        SENS_COUNTER_16BIT = 0x20,
        SENS_OTHER = 0x7F,
    }

    public enum SensorUnit
    {
        UNITS_NONE = 0x00, //CONTACTS
        UNITS_CENTIGRADE = 0x01, //TEMPERATURE
        UNITS_VOLTS_DC = 0x02, //VOLTAGE
        UNITS_VOLTS_AC_PEAK = 0x03,//vOLTAGE
        UNITS_VOLTS_AC_RMS = 0x04,//vOLTAGE
        UNITS_AMPERE_DC = 0x05,//CURRENT
        UNITS_AMPERE_AC_PEAK = 0x06,//CURRENT
        UNITS_AMPERE_AC_RMS = 0x07,//CURRENT
        UNITS_HERTZ = 0x08,//FREQUENCY / ANG_VEL
        UNITS_OHM = 0x09,//RESISTANCE
        UNITS_WATT = 0x0A,//POWER
        UNITS_KILOGRAM = 0x0B,//MASS
        UNITS_METERS = 0x0C,//LENGTH / POSITION
        UNITS_METERS_SQUARED = 0x0D,//AREA
        UNITS_METERS_CUBED = 0x0E,//VOLUME
        UNITS_KILOGRAMMES_PER_METER_CUBED = 0x0F,//DENSITY
        UNITS_METERS_PER_SECOND = 0x10,//VELOCITY
        UNITS_METERS_PER_SECOND_SQUARED = 0x11,//ACCELERATION
        UNITS_NEWTON = 0x12,//FORCE
        UNITS_JOULE = 0x13,//ENERGY
        UNITS_PASCAL = 0x14,//PRESSURE
        UNITS_SECOND = 0x15,//TIME
        UNITS_DEGREE = 0x16,//ANGLE
        UNITS_STERADIAN = 0x17,//ANGLE
        UNITS_CANDELA = 0x18,//LUMINOUS_INTENSITY
        UNITS_LUMEN = 0x19,//LUMINOUS_FLUX
        UNITS_LUX = 0x1A,//ILLUMINANCE
        UNITS_IRE = 0x1B,//CHROMINANCE
        UNITS_BYTE = 0x1C,//
    }

    public enum SensorUnitPrefix
    {
        PREFIX_NONE = 0x00, //MULTIPLY BY 1
        PREFIX_DECI = 0x00, //MULTIPLY BY 10^-1
        PREFIX_CENTI = 0x00, //MULTIPLY BY 10^-2
        PREFIX_MILLI = 0x00, //MULTIPLY BY 10^-3
        PREFIX_MICRO = 0x00, //MULTIPLY BY 10^-6
        PREFIX_NANO = 0x00, //MULTIPLY BY 10^-9
        PREFIX_PICO = 0x00, //MULTIPLY BY 10^-12
        PREFIX_FEMPTO = 0x00, //MULTIPLY BY 10^-15
        PREFIX_ATTO = 0x00, //MULTIPLY BY 10^-18
        PREFIX_ZEPTO = 0x00, //MULTIPLY BY 10^-21
        PREFIX_YOCTO = 0x00, //MULTIPLY BY 10^-24
        PREFIX_DECA = 0x00, //MULTIPLY BY 10^1
        PREFIX_HECTO = 0x00, //MULTIPLY BY 10^2
        PREFIX_KILO = 0x00, //MULTIPLY BY 10^3
        PREFIX_MEGA = 0x00, //MULTIPLY BY 10^6
        PREFIX_GIGA = 0x00, //MULTIPLY BY 10^9
        PREFIX_TERRA = 0x00, //MULTIPLY BY 10^12
        PREFIX_PETA = 0x00, //MULTIPLY BY 10^15 
        PREFIX_EXA = 0x00, //MULTIPLY BY 10^18
        PREFIX_ZETTA = 0x00, //MULTIPLY BY 10^21
        PREFIX_YOTTA = 0x00, //MULTIPLY BY 10^24
    }
        //    Notes:
        //When a prefix is used with MEMORY, the multiplier refers to binary multiple.i.e.KILO means
        //multiply by 1024.
        //When a prefix is used with MASS, note that the UNIT is Kilogram.The prefix PREFIX_MILLI is 
        //used to denote grams.

    public enum DataType
    {
        DS_NOT_DEFINED = 0x00, // NOT DEFINED
        DS_BIT_FIELD = 0x01, // DATA IS BIT PACKED
        DS_ASCII = 0x02, // DATA IS A STRING
        DS_UNSIGNED_BYTE = 0x03, //DATA IS AN ARRAY OF UNSIGNED BYTES
        DS_SIGNED_BYTE = 0x04, //DATA IS AN ARRAY OF SIGNED BYTES
        DS_UNSIGNED_WORD = 0x05, //DATA IS AN ARRAY OF UNSIGNED 16-BIT WORDS
        DS_SIGNED_WORD = 0x06, //DATA IS AN ARRAY OF SIGNED 16-BIT WORDS
        DS_UNSIGNED_DWORD = 0x07, //DATA IS AN ARRAY OF UNSIGNED 32-BIT WORDS
        DS_SIGNED_DWORD = 0x08, //DATA IS AN ARRAY OF SIGNED 32-BIT WORDS
    }

    public enum ParameterDescriptionCommandClass
    {
        CC_GET = 0x01, //PID Supports Get Only
        CC_SET = 0x02, //PID Supports Set Only
        CC_GET_SET = 0x03, //PID Supports Get & Set
    }

    public enum ResponseNACKReason
    {
        NR_UNKNOWN_PID = 0x0000, // THE RESPONDER CANNOT COMPLY WITH THE REQUEST BECAUSE THE MESSAGE IS NOT IMPLIMENTED IN RESPONDER
        NR_FORMAT_ERROR = 0x0001, //THE RESPONDER CANNOT INTERPRET REQUEST AS CONTROLLER DATA WAS NOT FORMATTED CORRECTLY
        NR_HARDWARE_FAULT = 0X002, // THE RESPONDER CANNOT COMPLY DUE TO AN INTERNAL HARDWARE FAULT
        NR_PROXY_REJECT = 0X0003, //PROXY IS NOT THE RDM LINE MASTER AND CANNOT COMPLY WITH MESSAGE
        NR_WRITE_PROTEXT = 0X0004, //SET COMMAND NORMALLY ALLOWED BUT BEING BLOCKED CURRENTLY
        NR_UNSUPPORTED_COMMAND_CLASS = 0X0005, //NOT VALID FOR COMMAND CLASS ATTEMPTED. MAY BE USED WHERE GET ALOWED BUT SET IS NOT SUPPORTED.
        NR_DATA_OUT_OF_RANGE = 0x0006, // VALUE FOR GIVEN PARAMETER OUT OF ALLOWABLE RANGE OR NOT SUPPORT
        NR_BUFFER_FULL = 0x0007, // BUFFER OR QUEUE SPACE CURRENTLY HAS NO FREE SPACE TO STORE DATA
        NR_PACKET_SIZE_UNSUPPORTED = 0x0008, //INCOMING MESSAGE EXCEEDS BUFFER CAPACITY
        NR_SUB_DEVICE_OUT_OF_RANGE = 0x0009, //SUB-DEVICE IS OUT OF RANGE OF UNKNOWN
        NR_PROXY_BUFFER_FULL = 0X000A, // THE PROXY BUFFER IS FULL AND CAN NOT STORE ANY MORE QUEUED MESSAGE OR STATUS MESSAGE RESPONSES.
    }


}
